# Generated by Django 5.2.14 on 2026-05-22 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('tipo', models.CharField(default='1X2', max_length=32)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('deporte', models.CharField(default='futbol', max_length=64)),
                ('equipo_local', models.CharField(max_length=120)),
                ('equipo_visitante', models.CharField(max_length=120)),
                ('inicio_programado', models.DateTimeField()),
                ('status', models.CharField(choices=[('programado', 'Programado'), ('en_vivo', 'En vivo'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido'), ('anulado', 'Anulado')], default='programado', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['inicio_programado'],
            },
        ),
        migrations.CreateModel(
            name='MarketSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=64)),
                ('codigo', models.CharField(max_length=16)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='betting.market')),
            ],
            options={
                'unique_together': {('market', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='market',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='betting.sportevent'),
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stake', models.DecimalField(decimal_places=4, max_digits=18)),
                ('odds_locked', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('accepted', 'Aceptada'), ('won', 'Ganada'), ('lost', 'Perdida'), ('void', 'Anulada')], default='accepted', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ledger_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.ledgertransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets', to=settings.AUTH_USER_MODEL)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='betting.marketselection')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='betting.sportevent')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
