# Generated by Django 5.2.14 on 2026-05-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_valores_es_apuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuesta',
            name='odds_locked',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cuota bloqueada'),
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='stake',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='monto'),
        ),
        migrations.AlterField(
            model_name='seleccionmercado',
            name='odds',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cuota'),
        ),
    ]
