# Generated by Django 5.2.14 on 2026-05-23 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_alter_apuesta_odds_locked_alter_apuesta_stake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventodeportivo',
            name='seleccion_ganadora',
            field=models.ForeignKey(blank=True, help_text='Selección ganadora del mercado 1X2 (para liquidar apuestas).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_ganados', to='betting.seleccionmercado', verbose_name='selección ganadora'),
        ),
    ]
