# Generated by Django 5.2.14 on 2026-05-23 17:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0005_nivel1_completo'),
        ('wallet', '0004_rename_wallet_ledg_user_id_84261c_idx_wallet_asie_user_id_b2d765_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apuesta',
            name='cashout_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apuesta',
            name='cashout_monto',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='monto cash-out'),
        ),
        migrations.AddField(
            model_name='mercado',
            name='suspendido_hasta',
            field=models.DateTimeField(blank=True, help_text='In-play: mercado pausado tras gol/expulsión hasta esta hora.', null=True),
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='status',
            field=models.CharField(choices=[('aceptada', 'Aceptada'), ('ganada', 'Ganada'), ('perdida', 'Perdida'), ('anulada', 'Anulada'), ('cashout', 'Cash-out')], default='aceptada', max_length=16, verbose_name='estado'),
        ),
        migrations.CreateModel(
            name='ApuestaCombinada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stake', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='monto')),
                ('odds_locked', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='cuota combinada')),
                ('status', models.CharField(choices=[('aceptada', 'Aceptada'), ('ganada', 'Ganada'), ('perdida', 'Perdida'), ('anulada', 'Anulada'), ('cashout', 'Cash-out')], default='aceptada', max_length=16, verbose_name='estado')),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('transaccion_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.transaccioncontable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apuestas_combinadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apuesta combinada',
                'verbose_name_plural': 'Apuestas combinadas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PiernaCombinada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odds_locked', models.DecimalField(decimal_places=2, max_digits=10)),
                ('combinada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piernas', to='betting.apuestacombinada')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='betting.eventodeportivo')),
                ('seleccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='betting.seleccionmercado')),
            ],
            options={
                'verbose_name': 'Pierna combinada',
                'verbose_name_plural': 'Piernas combinadas',
                'unique_together': {('combinada', 'evento')},
            },
        ),
    ]
