# Generated by Django 5.2.14 on 2026-05-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_nombres_es'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='limite_deposito_diario_pendiente',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Nuevo límite diario que aplica tras 24 h si es mayor al actual', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='limite_deposito_mensual',
            field=models.DecimalField(decimal_places=4, default=5000, help_text='Máximo de fichas que puede recargar por mes', max_digits=18),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='limite_deposito_semanal',
            field=models.DecimalField(decimal_places=4, default=2000, help_text='Máximo de fichas que puede recargar por semana', max_digits=18),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='limite_efectivo_desde',
            field=models.DateTimeField(blank=True, help_text='Momento en que entra en vigor el límite diario pendiente', null=True),
        ),
    ]
