# Generated by Django 5.2.14 on 2026-05-22 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=64)),
                ('referencia', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('wallet_usuario', 'Wallet del usuario'), ('casa', 'Casa / operador'), ('apuestas_pendientes', 'Fondos bloqueados en apuestas'), ('bonos', 'Bonos promocionales')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('direction', models.CharField(choices=[('DEBIT', 'Débito'), ('CREDIT', 'Crédito')], max_length=8)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='wallet.ledgertransaction')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'account'], name='wallet_ledg_user_id_84261c_idx'), models.Index(fields=['account'], name='wallet_ledg_account_863245_idx')],
            },
        ),
    ]
